version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  rspec:
    build:
      context: ./backend
      dockerfile: Dockerfile.rspec
    volumes:
      - ./backend:/app
    depends_on:
      - db